project_id = "iufbhrfvsjassqderjgq"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-reset-password-email]
verify_jwt = false

[functions.reset-password]
verify_jwt = false